# Generated by Django 2.2.11 on 2021-07-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitors', models.IntegerField()),
                ('title', models.TextField()),
                ('post', models.TextField()),
                ('post_json', models.TextField()),
                ('thumbnail', models.TextField()),
                ('caption', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
